apiVersion: appplatform.azure.upbound.io/v1beta2
kind: SpringCloudBuildDeployment
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta2/springcloudbuilddeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    buildResultId: <default>
    environmentVariables:
      Env: Staging
      Foo: Bar
    instanceCount: 2
    quota:
    - cpu: "2"
      memory: 4Gi
    springCloudAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta2/springcloudbuilddeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

apiVersion: appplatform.azure.upbound.io/v1beta2
kind: SpringCloudApp
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta2/springcloudbuilddeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: appplatform.azure.upbound.io/v1beta2
kind: SpringCloudService
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta2/springcloudbuilddeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: E0
