apiVersion: resources.azure.upbound.io/v1beta1
kind: ResourceGroupTemplateDeployment
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/resourcegrouptemplatedeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deploymentMode: Incremental
    parametersContent: |-
      ${jsonencode({
          "vnetName" = {
            value = local.vnet_name
          }
        })}
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    templateContent: |
      {
          "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
          "contentVersion": "1.0.0.0",
          "parameters": {
              "vnetName": {
                  "type": "string",
                  "metadata": {
                      "description": "Name of the VNET"
                  }
              }
          },
          "variables": {},
          "resources": [
              {
                  "type": "Microsoft.Network/virtualNetworks",
                  "apiVersion": "2020-05-01",
                  "name": "[parameters('vnetName')]",
                  "location": "[resourceGroup().location]",
                  "properties": {
                      "addressSpace": {
                          "addressPrefixes": [
                              "10.0.0.0/16"
                          ]
                      }
                  }
              }
          ],
          "outputs": {
            "exampleOutput": {
              "type": "string",
              "value": "someoutput"
            }
          }
      }

---

