apiVersion: dbformariadb.azure.upbound.io/v1alpha2
kind: Configuration
metadata:
  name: example-mariadb-configuration
spec:
  forProvider:
    #  Specifies the name of the MariaDB Configuration, which needs to be a valid MariaDB configuration name.
    #  See https://mariadb.com/kb/en/server-system-variables/
    name: interactive_timeout
    resourceGroupNameRef:
      name: example
    serverName: example-mariadb-server
    value: "600"
  providerConfigRef:
    name: default
