apiVersion: eventhub.azure.m.upbound.io/v1beta1
kind: NamespaceDisasterRecoveryConfig
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/namespacedisasterrecoveryconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    namespaceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    partnerNamespaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: secondary
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: eventhub.azure.m.upbound.io/v1beta1
kind: EventHubNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/namespacedisasterrecoveryconfig
  labels:
    testing.upbound.io/example-name: primary
  name: primary
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard

---

apiVersion: eventhub.azure.m.upbound.io/v1beta1
kind: EventHubNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/namespacedisasterrecoveryconfig
  labels:
    testing.upbound.io/example-name: secondary
  name: secondary
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    sku: Standard

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: eventhub/v1beta1/namespacedisasterrecoveryconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
