apiVersion: network.azure.upbound.io/v1beta1
kind: ApplicationSecurityGroup
metadata:
  name: example
spec:
  forProvider:
    location: West Europe
    resourceGroupNameRef:
      name: example
    tags:
      Hello: World
  providerConfigRef:
    name: example
