apiVersion: logic.azure.upbound.io/v1beta2
kind: AppIntegrationAccountBatchConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta2/appintegrationaccountbatchconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    batchGroupName: TestBatchGroup
    integrationAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: exampleiabc
    releaseCriteria:
    - messageCount: 80
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: logic.azure.upbound.io/v1beta1
kind: AppIntegrationAccount
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta2/appintegrationaccountbatchconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
    name: example-ia
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: Standard

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: logic/v1beta2/appintegrationaccountbatchconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe
