# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: resources.azure.m.upbound.io/v1beta1
kind: ResourceDeploymentScriptAzurePowerShell
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/resourcedeploymentscriptazurepowershell
  labels:
    testing.upbound.io/example-name: example
  name: rdsapsex
  namespace: upbound-system
spec:
  forProvider:
    cleanupPreference: OnSuccess
    commandLine: -name "John Dole"
    forceUpdateTag: "1"
    identity:
      identityIdsRefs:
        - name: rdsapsex
      type: UserAssigned
    location: West Europe
    name: rdsapsex
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    retentionInterval: P1D
    scriptContent: |2
                param([string] $name)
                  $output = 'Hello {0}.' -f $name
                  Write-Output $output
                  $DeploymentScriptOutputs = @{}
                  $DeploymentScriptOutputs['text'] = $output
    tags:
      key: value
    timeout: PT30M
    version: "8.3"
---
apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta1/resourcedeploymentscriptazurepowershell
  labels:
    testing.upbound.io/example-name: example
  name: rdsapsex
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
---
apiVersion: managedidentity.azure.m.upbound.io/v1beta1
kind: UserAssignedIdentity
metadata:
  annotations:
    meta.upbound.io/example-id: resources/v1beta2/resourcedeploymentscriptazurepowershell
  labels:
    testing.upbound.io/example-name: example
  name: rdsapsex
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    name: rdsapsex
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
