apiVersion: containerapp.azure.m.upbound.io/v1beta1
kind: EnvironmentCustomDomain
metadata:
  annotations:
    meta.upbound.io/example-id: containerapp/v1beta1/environmentcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    certificateBlobBase64: ${filebase64("testacc.pfx")}
    certificatePasswordSecretRef:
      key: example-key
      name: example-secret
    containerAppEnvironmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    dnsSuffix: acceptancetest.contoso.com

---

apiVersion: containerapp.azure.m.upbound.io/v1beta1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: containerapp/v1beta1/environmentcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    logAnalyticsWorkspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: operationalinsights.azure.m.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: containerapp/v1beta1/environmentcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    retentionInDays: 30
    sku: PerGB2018

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: containerapp/v1beta1/environmentcustomdomain
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
