apiVersion: insights.azure.upbound.io/v1beta1
kind: ApplicationInsightsWebTest
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightswebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationInsightsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configuration: |
      <WebTest Name="WebTest1" Id="ABD48585-0831-40CB-9069-682EA6BB3583" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="" ResultsLocale="">
        <Items>
          <Request Method="GET" Guid="a5f10126-e4cd-570d-961c-cea43999a200" Version="1.1" Url="http://microsoft.com" ThinkTime="0" Timeout="300" ParseDependentRequests="True" FollowRedirects="True" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="200" ExpectedResponseUrl="" ReportingName="" IgnoreHttpStatusCode="False" />
        </Items>
      </WebTest>
    enabled: true
    frequency: 300
    geoLocations:
    - us-tx-sn1-azr
    - us-il-ch1-azr
    kind: ping
    location: West Europe
    name: tf-test-appinsights-webtest
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    timeout: 60

---

apiVersion: insights.azure.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightswebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationType: web
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightswebtest
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

