# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: compute.azure.upbound.io/v1beta1
kind: GalleryApplicationVersion
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversion
  name: galleryappversion
spec:
  forProvider:
    name: 1.0.0
    galleryApplicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversiongalleryapp
    location: West Europe
    manageAction:
    - install: '[install command]'
      remove: '[remove command]'
    source:
    - mediaLinkSelector:
        matchLabels:
          testing.upbound.io/example-name: galleryappversionstorblob
    targetRegion:
    - nameSelector:
        matchLabels:
          testing.upbound.io/example-name: galleryappversiongalleryapp
      regionalReplicaCount: 1

---

apiVersion: compute.azure.upbound.io/v1beta1
kind: GalleryApplication
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversiongalleryapp
  name: galleryappversiongalleryapp
spec:
  forProvider:
    galleryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversiongallery
    location: West Europe
    supportedOsType: Linux

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversionrg
  name: galleryappversionrg
spec:
  forProvider:
    location: West Europe

---

apiVersion: compute.azure.upbound.io/v1beta1
kind: SharedImageGallery
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversiongallery
  name: galleryappversiongallery
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionrg

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversionstoracc
  name: galleryappversionstoracc
spec:
  forProvider:
    accountReplicationType: LRS
    accountTier: Standard
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionrg

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Blob
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversionstorblob
  name: galleryappversionstorblob
spec:
  forProvider:
    sourceContent: '[scripts file content]'
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionstoracc
    storageContainerNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionstorcont
    type: Block

---

apiVersion: storage.azure.upbound.io/v1beta1
kind: Container
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/galleryapplicationversion
  labels:
    testing.upbound.io/example-name: galleryappversionstorcont
  name: galleryappversionstorcont
spec:
  forProvider:
    containerAccessType: blob
    storageAccountNameSelector:
      matchLabels:
        testing.upbound.io/example-name: galleryappversionstoracc
