# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: dbforpostgresql.azure.m.upbound.io/v1beta1
kind: FlexibleServerConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1beta1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    name: backslash_quote
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    value: "on"

---

apiVersion: dbforpostgresql.azure.m.upbound.io/v1beta1
kind: FlexibleServer
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1beta1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: GP_Standard_D4s_v3
    storageMb: 32768
    version: "12"

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbforpostgresql/v1beta1/flexibleserverconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
