apiVersion: dbformariadb.azure.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: interactive_timeout
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serverNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    value: "600"

---

apiVersion: dbformariadb.azure.upbound.io/v1beta1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    administratorLogin: mariadbadmin
    administratorLoginPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    skuName: B_Gen5_2
    ssl_enforcement: Enabled
    storage_profile:
    - backup_retention_days: 7
      geo_redundant_backup: Disabled
      storage_mb: 5120
    version: "10.2"

---

apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: dbformariadb/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    location: West Europe

---

