# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: desktopvirtualization.azure.m.upbound.io/v1beta1
kind: VirtualDesktopApplicationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: desktopvirtualization/v1beta1/virtualdesktopapplicationgroup
  labels:
    testing.upbound.io/example-name: virtualdesktopapplicationgroupns
  name: virtualdesktopapplicationgroupns
  namespace: upbound-system
spec:
  forProvider:
    description: 'Acceptance Test: An application group'
    friendlyName: TestAppGroup
    hostPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: virtualdesktopapplicationgroupns
    location: westeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: virtualdesktopapplicationgroupns
    type: RemoteApp

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: desktopvirtualization/v1beta1/virtualdesktopapplicationgroup
  labels:
    testing.upbound.io/example-name: virtualdesktopapplicationgroupns
  name: virtualdesktopapplicationgroupns
  namespace: upbound-system
spec:
  forProvider:
    location: westeurope

---

apiVersion: desktopvirtualization.azure.m.upbound.io/v1beta1
kind: VirtualDesktopHostPool
metadata:
  annotations:
    meta.upbound.io/example-id: desktopvirtualization/v1beta1/virtualdesktopapplicationgroup
  labels:
    testing.upbound.io/example-name: virtualdesktopapplicationgroupns
  name: virtualdesktopapplicationgroupns
  namespace: upbound-system
spec:
  forProvider:
    loadBalancerType: BreadthFirst
    location: westeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: virtualdesktopapplicationgroupns
    type: Pooled
