# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: guestconfiguration.azure.upbound.io/v1beta1
kind: PolicyVirtualMachineConfigurationAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    configuration:
    - assignmentType: ApplyAndMonitor
      parameter:
      - name: Minimum Password Length;ExpectedValue
        value: "16"
      - name: Minimum Password Age;ExpectedValue
        value: "0"
      - name: Maximum Password Age;ExpectedValue
        value: 30,45
      - name: Enforce Password History;ExpectedValue
        value: "10"
      - name: Password Must Meet Complexity Requirements;ExpectedValue
        value: "1"
      version: 1.*
    location: West Europe
    virtualMachineIdSelector:
      matchLabels:
        testing.upbound.io/example-name: examplewind
---
apiVersion: network.azure.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    ipConfiguration:
    - name: internal
      privateIpAddressAllocation: Dynamic
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rgconfigurationassignment
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: rgconfigurationassignment
  name: rgconfigurationassignment
spec:
  forProvider:
    location: West Europe
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressPrefixes:
    - 10.0.2.0/24
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rgconfigurationassignment
    virtualNetworkNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    addressSpace:
    - 10.0.0.0/16
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rgconfigurationassignment
---
apiVersion: compute.azure.upbound.io/v1beta1
kind: WindowsVirtualMachine
metadata:
  annotations:
    meta.upbound.io/example-id: guestconfiguration/v1beta1/policyvirtualmachineconfigurationassignment
  labels:
    testing.upbound.io/example-name: examplewind
  name: examplewind
spec:
  forProvider:
    adminPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    adminUsername: adminuser
    identity:
      - type: SystemAssigned
    location: West Europe
    networkInterfaceIdsRefs:
      - name: example
    osDisk:
      - caching: ReadWrite
        storageAccountType: Standard_LRS
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: rgconfigurationassignment
    size: Standard_F2
    sourceImageReference:
      - offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
---
apiVersion: v1
data:
  example-key: dXBiMHVuZHIwY2s1ITMxMzM3Cg==
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
