# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: appplatform.azure.m.upbound.io/v1beta1
kind: SpringCloudJavaDeployment
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta1/springcloudjavadeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    environmentVariables:
      Env: Staging
      Foo: Bar
    instanceCount: 2
    jvmOptions: -XX:+PrintGC
    quota:
      cpu: "2"
      memory: 4Gi
    runtimeVersion: Java_11
    springCloudAppIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta1/springcloudjavadeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe

---

apiVersion: appplatform.azure.m.upbound.io/v1beta1
kind: SpringCloudApp
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta1/springcloudjavadeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    identity:
      type: SystemAssigned
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: appplatform.azure.m.upbound.io/v1beta1
kind: SpringCloudService
metadata:
  annotations:
    meta.upbound.io/example-id: appplatform/v1beta1/springcloudjavadeployment
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
