# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: servicenetworking.azure.m.upbound.io/v1beta1
kind: ApplicationLoadBalancer
metadata:
  annotations:
    meta.upbound.io/example-id: servicenetworking/v1beta1/applicationloadbalancer
  labels:
    testing.upbound.io/example-name: applicationloadbalancerns
  name: applicationloadbalancerns
  namespace: upbound-system
spec:
  forProvider:
    location: westeurope
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: applicationloadbalancerns

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: servicenetworking/v1beta1/applicationloadbalancer
  labels:
    testing.upbound.io/example-name: applicationloadbalancerns
  name: applicationloadbalancerns
  namespace: upbound-system
spec:
  forProvider:
    location: westeurope
