apiVersion: appconfiguration.azure.m.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: appconfiguration/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: appconf
  name: appconf
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: appconfiguration/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
