apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsightsAnalyticsItem
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsanalyticsitem
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    applicationInsightsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    content: requests //simple example query
    name: testquery
    scope: shared
    type: query

---

apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsanalyticsitem
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    applicationType: web
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsanalyticsitem
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
