apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsightsAPIKey
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsapikey
  labels:
    testing.upbound.io/example-name: read_telemetry
  name: read-telemetry
  namespace: upbound-system
spec:
  forProvider:
    applicationInsightsIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: tf-test-appinsights-read-telemetry-api-key
    readPermissions:
    - aggregate
    - api
    - draft
    - extendqueries
    - search

---

apiVersion: insights.azure.m.upbound.io/v1beta1
kind: ApplicationInsights
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsapikey
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    applicationType: web
    location: West Europe
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: azure.m.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  annotations:
    meta.upbound.io/example-id: insights/v1beta1/applicationinsightsapikey
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    location: West Europe
